---
- name: test
  hosts: all
  remote_user: ansible
  become: true
  gather_facts: true
  tasks:
    
    - name: Ensure running OS in rhel7
      assert:
        fail_msg: Selected server is not a RedHat 7 system. Please choose a RedHat 7 system to proceed
        that:
          - ansible_facts.distribution == "RedHat" and
          - ansible_facts.distribution_major_version= "7"