---
- name: Changing the interface names from eth by importing tasks and variables
  ansible.builtin.import_tasks: interface_rename.yml


- name: Remove obsolete kernel drivers importing tasks and variables
  ansible.builtin.import_tasks: remove_obsolete_driver.yml
  

