---
- name: Collect only selected facts
  ansible.builtin.setup:
    filter:
      - 'ansible_distribution'

- name: Only continue if the system is rhel7
  ansible.builtin.assert:
    fail_msg: "Selected server is not a RedHat 7 system. Please choose a RedHat 7 system to proceed"
    that:
      - ansible_facts['distribution'] == "RedHat"
      - ansible_facts['distribution_major_version'] == "7"
#use ansible_distribution

- name: Ensure subscription-manager is latest
  ansible.builtin.yum:
    name: subscription-manager
    state: latest

- name: Checking system registration
  ansible.builtin.command: subscription-manager identity
  register: registration_status
  ignore_errors: true

- name: showing registration status
  debug:
    var: registration_status.stderr_lines

- name: Registering and subscribing system to RHN
  redhat_subscription:
    state: present
    username: rh-ee-deray
    password: J289scarface@p2345
    auto_attach: true
  when: registration_status.rc == 1
#  register: subscription_status
#  changed_when:
#    - subscription_status.rc == 0

#need to check rhsm availability in Barclays systems
- name: Ensure the repositories are enabled
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rhel7_repositories }}"

#needs to be changed as per Barclays standards
- name: Unsetting subscription-manager release
  rhsm_release:
    release: null

- name: Checking yum versionlock package availability
  ansible.builtin.yum:
    list: yum-plugin-versionlock
  register: package_result
  ignore_errors: true

- name: Yum version lock remove
  community.general.yum_versionlock:
    state: absent
    name: '*'
  when: package_result['results'][0]['yumstate'] == "installed"

- name: Update the system using yum
  ansible.builtin.yum:
    name: '*'
    state: latest
  async: 2000
  poll: 0
  register: patch_result

- name: Check patch result
  async_status:
    jid: "{{ patch_result['ansible_job_id'] }}"
  register: async_poll_results
  until: async_poll_results['finished']
  retries: 10
  delay: 60

- name: Show results
  debug:
    var: async_poll_results

- name: Ensure the result is successfull
  ansible.builtin.assert:
    that:
      - async_poll_results['rc'] == 0

- name: Nothing to patch
  ansible.builtin.debug:
    msg: "No patch available"
  when:
    - async_poll_results['rc'] == 0
    - not async_poll_results['changed']

- name: Applied patches
  ansible.builtin.debug:
    msg: async_poll_results['results']
  when:
    - async_poll_results['rc'] == 0
    - async_poll_results['changed']
  
- name: Check if the system needs a reboot
  ansible.builtin.assert:
    fail_msg: Server has failed pathcing doesn't need a reboot.
    that: async_poll_results['rc'] == 0
#  notify:
#    - reboot system

- name: reboot system
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: async_poll_results['rc'] == 0

- name: Installing cockpit-leapp
  ansible.builtin.yum:
    name: cockpit-leapp
    state: present

- name: Installing leapp utility
  ansible.builtin.yum:
    name: leapp-upgrade
    state: latest

- name: Copy CHEF_RUNS_DISABLED using file lookup plugin to pause all Chef actions on the host
  ansible.builtin.copy:
    content: "{{ lookup('file', 'files/CHEF_RUNS_DISABLED') }}"
    dest: /etc/chef/CHEF_RUNS_DISABLED
  ignore_errors: true

#enabling rhel8 repositories
#- name: Enabling rhel8 repositories for leapp assessment
#  community.general.rhsm_repository:
#    name: "{{ item }}"
#    stats: enabled
#  loop: "{{ rhel8_repositories }}"

#Run upgrade in the lab to check the condition of success
- name: Running the upgrade assessment
  ansible.builtin.command: leapp preupgrade
  register: leapp_report_status
  failed_when:
    - '"Answerfile has been generated at /var/log/leapp/answerfile" not in leapp_report_status.stdout'
    - '"Answerfile has been generated at /var/log/leapp/answerfile" not in leapp_report_status.stderr'

- name: Displaying the output of preupgrade asessment running
  ansible.builtin.debug:
    var: leapp_report_status.stdout_lines
