---
- name: Provide confirmation in answer file
  ansible.builtin.lineinfile:
    path: /var/log/leapp/answerfile
    line: confirm = True

- name: Running the upgrade assessment
  ansible.builtin.command: leapp preupgrade
  register: leapp_report_status
  failed_when:
    - '"Answerfile has been generated at /var/log/leapp/answerfile" not in leapp_report_status.stdout'
    - '"Answerfile has been generated at /var/log/leapp/answerfile" not in leapp_report_status.stderr'

- name: Displaying the output of preupgrade asessment running
  ansible.builtin.debug:
    var: leapp_report_status.stdout_lines